#!/bin/sh

set -e -x

# Kernel Source
KERNEL_SOURCE="https://github.com/malkist01/j6plus_arm"
KERNEL_BRANCH="19.1"
KERNEL_DEFCONFIG="teletubies_defconfig"

# Prebuilt Clang Toolchain (AOSP)
GCC_x32="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9"
GCC_BRANCH="master-kernel-build-2021"

# Setup make Command
make_fun() {
	make O=out ARCH=arm
		CROSS_COMPILE=arm-linux-androideabi- "$@"
}

# Work Path
WORK="${HOME}/work"

# Kernel Folder Name
KERNEL="myKernel"

# Kernel Source Path
KERNEL_SRC="${WORK}/${KERNEL}"

# Prepare Directory
mkdir -p "${WORK}"
cd "${WORK}" || exit 1

# Cloning all the Necessary files
git clone --depth=1 "${GCC_x32}" -b "${GCC_BRANCH}" ./x32
git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"

# Setting Toolchain Path
PATH="${WORK}/x32/bin:/bin"

# Enter Kernel root directory
cd "${KERNEL_SRC}" || exit 1

# KernelSU - Disable if not building one.

  echo "CONFIG_KSU=y" >> ./arch/arm/configs/teletubies_defconfig
# echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y" >> ./arch/arm/configs/teletubies_defconfig
  echo "CONFIG_KSU_TOOLKIT_SUPPORT=y" >> ./arch/arm/configs/teletubies_defconfig
#  wget https://raw.githubusercontent.com/TheSillyOk/kernel_ls_patches/refs/heads/master/scope-min-hooks-v1.9.patch
#  patch -p1 < scope-min-hooks-v1.9.patch
 curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/syscall_hook_patches.sh" | bash -s
 curl -LSs https://raw.githubusercontent.com/backslashxx/KernelSU/master/kernel/setup.sh | bash -s master

# Start Compiling Kernel
make_fun "${KERNEL_DEFCONFIG}"
make_fun -j"$(nproc --all)" 2>&1 | tee build.log 
